version: '3'

services:
  calculator:
    build:
      context: .
    restart: unless-stopped
    working_dir: /calculator/
    ports:
      - 8081:80
    volumes:
      - ./:/calculator/
    environment:
      # For Linux, replace the line below with hostname,
      # by executing `hostname` in Terminal.
      XDEBUG_CONFIG: remote_host=host.docker.internal, remote_port=9001